### ISSUE TITLE
Configuration File

### ISSUE THREAD

**Issue by FGDATA** [JWocky/JH-Launcher#3]
A few recommendations about JHLConfig.xml

1. Create a template. If the file is template, open the launcher in an empty Settings place so user can create his own settings (instead of inheriting Jwockys while making Jwocky's settings public)

2. Make the JHLConfig.xml file not trackeable by git, so regardless of user, the source code appears only to always have the empty template

3. If the JHLConfig is an empty template the `java JHL` opens on an empty tree of Settings page

4. Make the JHL able to `SAVE` the Settings in the Config file

4. Make the JHL reading the Config File (if not empty template) at launch, as it currently overwrites the whole Config content to JWocky's configuration when program is launched

**Comment by JWocky** [comment]
1.) + 2.) + 3.) still hanging, it's all the same problem
4.) can do with next version
empty template= non-existing JHLConfig.xml
